### ISSUE TITLE
Seek a way to force install specific binary

### ISSUE THREAD

**Issue by zxdong262** [kribblo/node-ffmpeg-installer#19]
I am working on mac, but would upload packages to aws lamda, which is linux platform, I hope there is a way to install specific binary.

**Comment by kribblo** [comment]
Hello! Yes, that is the purpose of this project: if you add this as a dependency to your project, it will install Mac binary on Mac and Linux binary on Linux.

**Comment by zxdong262** [comment]
@zxdong262 I mean the target is install linux pack in mac os with some flag maybe, that way I could build a package and uplaod to aws lamda.

**Comment by kribblo** [comment]
Ok, sorry, my misunderstanding. I guess that would be if you can override `process.package` and `process.cpu` when building, because there is no logic involved in this project, just using the built-in node controls. If you find a good way to do this I'll be happy to take a pull request for configuration and/or documentation!

**Comment by zxdong262** [comment]
@kribblo Thank you for the tip.

**Comment by kribblo** [comment]
That should be `process.os`, not package, sorry! Not sure if it can be done but if you find a solution I would be interested in documenting it in the README!
