### ISSUE TITLE
It does not support win32?

### ISSUE THREAD

**Issue by jackple** [kribblo/node-ffmpeg-installer#20]
![image](https://user-images.githubusercontent.com/6183232/49847688-6ad1d800-fe0c-11e8-851c-3be0200a70e8.png)
![image](https://user-images.githubusercontent.com/6183232/49847694-72917c80-fe0c-11e8-899c-200cd4e82c36.png)

My electron app can run in `win-unpacked`
But it can not run in `win-ia32-unpacked` with error `undefined: undefined`

Someone know why?

**Comment by kribblo** [comment]
This is probably a question for the electron project, this project only downloads a binary and puts it in a known path, so if the binary is not broken, it could be the packaging? There's been an issue before where electron changes the path: #10 but don't know if that's the problem here. The error message is not really saying anything, is there a stack trace or debug log?

**Comment by jackple** [comment]
Sorry! I do not know how to log at this stage. I have switched another solution to solve my problem, but thank you! And I think this issue is meaningful, so I do not close it for the moment. Maybe you close it.
