### ISSUE TITLE
"Could not find ffmpeg executable" using 'app.asar.unpacked'

### ISSUE THREAD

**Issue by HaveAGitGat** [kribblo/node-ffmpeg-installer#26]
I'm trying to run this once packaged on Windows (electron packager). The folder containing ffmpeg.exe successfully unpacks. I then use:

`const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path.replace('app.asar', 'app.asar.unpacked');`

but I get the error 

`"Could not find ffmpeg executable"`

`tried ..,"resources\app.asar\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe"`

So it seems to be trying to find the file before it allows the path to be modified to include "app.asar.unpacked".

**Comment by HaveAGitGat** [comment]
Interestingly, the above works fine on linux. I've used the following as a solution on windows:

`var ffmpegPath = (path.join(__dirname, '\\node_modules\\@ffmpeg-installer\\win32-x64\\ffmpeg.exe' )).replace('app.asar', 'app.asar.unpacked')`

**Comment by kribblo** [comment]
Hmm. Yeah, the code is trying to verify that the file exists, actually only because of a requested fallback to NPM 2 by some user: https://github.com/kribblo/node-ffmpeg-installer/blob/master/index.js

Not sure why it would work on one platform and not the other though, seems, as you put it, interesting. :) Maybe the easiest way to fix it for everyone is to also check for the electron paths, seems a common enough use case. As in, adding more else ifs.

**Comment by whyboris** [comment]
I'm on version `"@ffmpeg-installer/ffmpeg": "1.0.18",`

I'm using the same command:
`const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path.replace('app.asar', 'app.asar.unpacked');`

It seems to work with my Electron:
https://github.com/whyboris/Video-Hub-App/blob/master/main-extract.ts#L26

🤷‍♂

**Comment by MetaiR** [comment]
I had the same problem with my electron which is built by electronforge, I manage to make it work by use this config for my asar in the package.json
"asar": { "unpack": "*.{node,dll,exe}" }

hope it helps those in need
