### ISSUE TITLE
Just support current platform ?

### ISSUE THREAD

**Issue by nic519** [kribblo/node-ffmpeg-installer#34]
I am using node to install node-ffmpeg-installer in mac environment. I only installed a Darwin version of ffmpeg. How can I download Darwin and Windows version of ffmpeg at the same time? Because my electron software needs to support two systems at the same time.

**Comment by nic519** [comment]
<img width="500" alt="WeChatde1eb3044d8ea756dd56375c56a2c938" src="https://user-images.githubusercontent.com/2610741/60511893-aa5b0580-9d05-11e9-93ed-a09bd73a9a7c.png">

**Comment by kribblo** [comment]
The purpose of this package is the exact opposite I'm afraid, to only install ffmpeg for the current OS (actually, for whatever node you are currently running). 

There is another, older NPM project (sorry don't remember the name) that installs ffmpeg for all OS's, maybe you can find that if you search. Otherwise, the only way I know is to run npm install using each OS's node version. If you can run install using Windows node.js it should work, but the whole point of this project is to not download ffmpeg for more than one OS.
